name: CustomGG
version: ${project.version}
main: com.fallenflame.core.customgg.CustomGG
authors: [JoeZwet]
description: Allow players to customize their "GG"s
website: https://fallenflame.com
database: true
commands:
  gg:
    usage: /gg
    description: GUIHandler custom gg text.
  customgg:
    usage: /customgg
    description: CustomGG command.